# Generated by Django 2.2 on 2020-12-11 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Neurotransmitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Supplement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('english_name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField()),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('item_weight', models.IntegerField()),
                ('portion_weight', models.DecimalField(decimal_places=2, max_digits=4)),
                ('daily_intakes', models.IntegerField()),
                ('meal_relation', models.CharField(choices=[('B', 'Before meal'), ('A', 'After meal')], max_length=1)),
                ('country_of_origin', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_discovery', models.DateField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Category')),
                ('neurotransmitters', models.ManyToManyField(to='catalog.Neurotransmitter')),
                ('tags', models.ManyToManyField(to='catalog.Tag')),
            ],
        ),
    ]
