# Generated by Django 2.2 on 2020-12-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='supplement',
            name='item_price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='supplement',
            name='meal_relation',
            field=models.CharField(choices=[('B', 'Before meal'), ('A', 'After meal'), ('W', 'With meal')], max_length=1),
        ),
        migrations.AlterField(
            model_name='supplement',
            name='portion_weight',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
