# Generated by Django 2.2 on 2020-12-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20201211_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplement',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplement',
            name='meal_relation',
            field=models.CharField(choices=[('B', 'Before meal'), ('W', 'With meal'), ('A', 'After meal')], max_length=1),
        ),
    ]
