# Generated by Django 2.2 on 2020-12-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20201211_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplement',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='supplement',
            name='bioavailability',
            field=models.DecimalField(decimal_places=2, default=0.05, max_digits=3),
            preserve_default=False,
        ),
    ]
