# Generated by Django 2.2 on 2020-12-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20201214_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplement',
            name='portion_weight',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
