# Generated by Django 2.2 on 2020-12-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20201214_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplement',
            old_name='daily_intakes',
            new_name='daily_intakes_max',
        ),
        migrations.RenameField(
            model_name='supplement',
            old_name='portion_weight',
            new_name='portion_weight_max',
        ),
        migrations.AddField(
            model_name='supplement',
            name='daily_intakes_min',
            field=models.IntegerField(default=0.3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplement',
            name='portion_weight_min',
            field=models.DecimalField(decimal_places=3, default=2, max_digits=5),
            preserve_default=False,
        ),
    ]
