# Generated by Django 2.2 on 2020-12-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20201214_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#123456', max_length=7),
            preserve_default=False,
        ),
    ]
