# Generated by Django 2.2 on 2020-12-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_category_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplement',
            name='english_name',
        ),
        migrations.AddField(
            model_name='neurotransmitter',
            name='color',
            field=models.CharField(default='#123456', max_length=7),
            preserve_default=False,
        ),
    ]
