# Generated by Django 2.2 on 2020-12-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20201225_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplement',
            name='neurotransmitters',
            field=models.ManyToManyField(to='catalog.Neurotransmitter'),
        ),
        migrations.AlterField(
            model_name='supplement',
            name='tags',
            field=models.ManyToManyField(to='catalog.Tag'),
        ),
    ]
