# Generated by Django 2.2 on 2020-12-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20201225_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplement',
            name='slug',
            field=models.SlugField(default='ashwagandha', max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
