# Generated by Django 2.2 on 2021-01-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20210103_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplement',
            name='slug',
            field=models.SlugField(blank=True, max_length=40, unique=True),
        ),
    ]
