# Generated by Django 3.1.6 on 2021-02-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_auto_20210214_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplement',
            name='polish_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
